/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface JoinRequest {
    status: JoinRequestStatus;
    principal: Principal;
    displayName?: string;
    profileId: string;
}
export interface WhitelistEntry {
    principal: Principal;
    timestamp: bigint;
    reason: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ProfileCreationEntry {
    organizationName: string;
    creator: Principal;
    profileId: string;
    timestamp: bigint;
}
export interface Need {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
}
export interface SuspiciousActivityFlag {
    principal: Principal;
    activityType: SuspiciousActivityType;
    timestamp: bigint;
    details: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SuspensionInfo {
    suspendedAt: bigint;
    suspendedBy: Principal;
    reason: string;
}
export interface Profile {
    id: string;
    bio?: string;
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address: string;
    functions: Array<FunctionType>;
    phone: string;
    profilePicture?: string;
}
export interface Event {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ResourceHave {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
}
export interface CategoryMatch {
    resourceIds: Array<string>;
    needIds: Array<string>;
    category: ResourceCategory;
}
export interface ProfileMember {
    principal: Principal;
    displayName?: string;
    role: ProfileRole;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface UserProfile {
    profileId: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum FunctionType {
    production = "production",
    education = "education",
    equipmentSpace = "equipmentSpace",
    wasteManagement = "wasteManagement",
    processing = "processing",
    distribution = "distribution"
}
export enum JoinRequestStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum ProfileRole {
    user = "user",
    clubAdmin = "clubAdmin"
}
export enum ResourceCategory {
    storageSpace = "storageSpace",
    other = "other",
    equipment = "equipment",
    publicity = "publicity",
    foodDrink = "foodDrink",
    distributionSpace = "distributionSpace",
    kitchenSpace = "kitchenSpace"
}
export enum SuspiciousActivityType {
    repeatedFailedRegistration = "repeatedFailedRegistration",
    unusualPattern = "unusualPattern",
    rapidAccountCreation = "rapidAccountCreation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addProfileMember(profileId: string, principal: Principal, role: ProfileRole): Promise<void>;
    adminAssignProfileMember(profileId: string, principal: Principal, role: ProfileRole): Promise<void>;
    adminClearSuspiciousActivityFlag(principal: Principal, timestamp: bigint): Promise<void>;
    adminCreateProfile(id: string, organizationName: string, functions: Array<FunctionType>, address: string, phone: string, email: string, bio: string | null, profilePicture: string | null): Promise<void>;
    adminDeleteUser(user: Principal): Promise<void>;
    adminRemoveUserFromGroup(profileId: string, user: Principal): Promise<void>;
    adminSuspendUser(user: Principal, reason: string): Promise<void>;
    adminUnsuspendUser(user: Principal): Promise<void>;
    approveJoinRequest(profileId: string, memberPrincipal: Principal, role: ProfileRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanOrphanedRecords(): Promise<void>;
    createEvent(id: string, creatorProfileId: string, location: string, description: string, time: bigint, image: string | null, needs: Array<string>): Promise<void>;
    createMemberProfile(profileId: string): Promise<void>;
    createNeed(id: string, profileId: string, description: string, category: ResourceCategory, startDate: bigint, endDate: bigint): Promise<void>;
    createResource(id: string, profileId: string, description: string, category: ResourceCategory): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    deleteNeed(id: string): Promise<void>;
    deleteProfile(id: string): Promise<void>;
    deleteResource(id: string): Promise<void>;
    denyJoinRequest(profileId: string, memberPrincipal: Principal): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAllNeeds(): Promise<Array<Need>>;
    getAllProfiles(): Promise<Array<Profile>>;
    getAllResources(): Promise<Array<ResourceHave>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryMatches(category: ResourceCategory): Promise<CategoryMatch | null>;
    getDisplayName(principal: Principal): Promise<string | null>;
    getEvent(id: string): Promise<Event | null>;
    getFileReference(path: string): Promise<FileReference>;
    getHistoricalWhitelist(): Promise<Array<WhitelistEntry>>;
    getJoinRequestStatus(_profileId: string): Promise<JoinRequestStatus>;
    getNeed(id: string): Promise<Need | null>;
    getPendingJoinRequestsForProfile(profileId: string): Promise<Array<JoinRequest>>;
    getProfile(id: string): Promise<Profile | null>;
    getProfileCreationLog(): Promise<Array<ProfileCreationEntry>>;
    getProfileMembers(profileId: string): Promise<Array<ProfileMember>>;
    getResourceHave(id: string): Promise<ResourceHave | null>;
    getSuspendedUsers(): Promise<Array<[Principal, SuspensionInfo]>>;
    getSuspiciousActivityFlags(): Promise<Array<SuspiciousActivityFlag>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isApprovalStateInitialized(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFileReferences(): Promise<Array<FileReference>>;
    recordRegistrationAttempt(): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    registerProfile(id: string, organizationName: string, functions: Array<FunctionType>, address: string, phone: string, email: string, bio: string | null, profilePicture: string | null): Promise<void>;
    removeProfileMember(profileId: string, principal: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    requestJoin(profileId: string): Promise<void>;
    resetBackendState(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchNeeds(searchTerm: string): Promise<Array<Need>>;
    searchProfiles(searchTerm: string): Promise<Array<Profile>>;
    searchResources(searchTerm: string): Promise<Array<ResourceHave>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setDisplayName(displayName: string): Promise<void>;
    updateEvent(id: string, location: string, description: string, time: bigint, image: string | null, needs: Array<string>): Promise<void>;
    updateProfile(id: string, organizationName: string, functions: Array<FunctionType>, address: string, phone: string, email: string, bio: string | null, profilePicture: string | null): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, CategoryMatch as _CategoryMatch, Event as _Event, FunctionType as _FunctionType, JoinRequest as _JoinRequest, JoinRequestStatus as _JoinRequestStatus, Need as _Need, Profile as _Profile, ProfileMember as _ProfileMember, ProfileRole as _ProfileRole, ResourceCategory as _ResourceCategory, ResourceHave as _ResourceHave, SuspiciousActivityFlag as _SuspiciousActivityFlag, SuspiciousActivityType as _SuspiciousActivityType, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addProfileMember(arg0: string, arg1: Principal, arg2: ProfileRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfileMember(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfileMember(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminAssignProfileMember(arg0: string, arg1: Principal, arg2: ProfileRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignProfileMember(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignProfileMember(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminClearSuspiciousActivityFlag(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminClearSuspiciousActivityFlag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminClearSuspiciousActivityFlag(arg0, arg1);
            return result;
        }
    }
    async adminCreateProfile(arg0: string, arg1: string, arg2: Array<FunctionType>, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async adminDeleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminRemoveUserFromGroup(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveUserFromGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveUserFromGroup(arg0, arg1);
            return result;
        }
    }
    async adminSuspendUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspendUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspendUser(arg0, arg1);
            return result;
        }
    }
    async adminUnsuspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnsuspendUser(arg0);
            return result;
        }
    }
    async approveJoinRequest(arg0: string, arg1: Principal, arg2: ProfileRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJoinRequest(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJoinRequest(arg0, arg1, to_candid_ProfileRole_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanOrphanedRecords(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanOrphanedRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanOrphanedRecords();
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string | null, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async createMemberProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemberProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemberProfile(arg0);
            return result;
        }
    }
    async createNeed(arg0: string, arg1: string, arg2: string, arg3: ResourceCategory, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNeed(arg0, arg1, arg2, to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNeed(arg0, arg1, arg2, to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createResource(arg0: string, arg1: string, arg2: string, arg3: ResourceCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createResource(arg0, arg1, arg2, to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResource(arg0, arg1, arg2, to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteNeed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNeed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNeed(arg0);
            return result;
        }
    }
    async deleteProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return result;
        }
    }
    async deleteResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async denyJoinRequest(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyJoinRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyJoinRequest(arg0, arg1);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNeeds(): Promise<Array<Need>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNeeds();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNeeds();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<ResourceHave>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryMatches(arg0: ResourceCategory): Promise<CategoryMatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryMatches(to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryMatches(to_candid_ResourceCategory_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisplayName(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayName(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayName(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getHistoricalWhitelist(): Promise<Array<WhitelistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalWhitelist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalWhitelist();
            return result;
        }
    }
    async getJoinRequestStatus(arg0: string): Promise<JoinRequestStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinRequestStatus(arg0);
                return from_candid_JoinRequestStatus_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinRequestStatus(arg0);
            return from_candid_JoinRequestStatus_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNeed(arg0: string): Promise<Need | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNeed(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNeed(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingJoinRequestsForProfile(arg0: string): Promise<Array<JoinRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingJoinRequestsForProfile(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingJoinRequestsForProfile(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileCreationLog(): Promise<Array<ProfileCreationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileCreationLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileCreationLog();
            return result;
        }
    }
    async getProfileMembers(arg0: string): Promise<Array<ProfileMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileMembers(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileMembers(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourceHave(arg0: string): Promise<ResourceHave | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceHave(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceHave(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuspendedUsers(): Promise<Array<[Principal, SuspensionInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuspendedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuspendedUsers();
            return result;
        }
    }
    async getSuspiciousActivityFlags(): Promise<Array<SuspiciousActivityFlag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuspiciousActivityFlags();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuspiciousActivityFlags();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isApprovalStateInitialized(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isApprovalStateInitialized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isApprovalStateInitialized();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async recordRegistrationAttempt(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordRegistrationAttempt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordRegistrationAttempt();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async registerProfile(arg0: string, arg1: string, arg2: Array<FunctionType>, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async removeProfileMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfileMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfileMember(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestJoin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestJoin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestJoin(arg0);
            return result;
        }
    }
    async resetBackendState(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetBackendState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetBackendState();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchNeeds(arg0: string): Promise<Array<Need>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNeeds(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNeeds(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProfiles(arg0: string): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProfiles(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProfiles(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchResources(arg0: string): Promise<Array<ResourceHave>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResources(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResources(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string | null, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: Array<FunctionType>, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryMatch_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryMatch): CategoryMatch {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FunctionType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FunctionType): FunctionType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequestStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequestStatus): JoinRequestStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequest_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequest): JoinRequest {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Need_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Need): Need {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileMember_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileMember): ProfileMember {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRole): ProfileRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceHave_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceHave): ResourceHave {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SuspiciousActivityFlag_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuspiciousActivityFlag): SuspiciousActivityFlag {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_SuspiciousActivityType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuspiciousActivityType): SuspiciousActivityType {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryMatch]): CategoryMatch | null {
    return value.length === 0 ? null : from_candid_CategoryMatch_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Need]): Need | null {
    return value.length === 0 ? null : from_candid_Need_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResourceHave]): ResourceHave | null {
    return value.length === 0 ? null : from_candid_ResourceHave_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image: [] | [string];
    creatorProfileId: string;
    location: string;
}): {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        time: value.time,
        description: value.description,
        needs: value.needs,
        image: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.image)),
        creatorProfileId: value.creatorProfileId,
        location: value.location
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: _ResourceCategory;
    startDate: bigint;
}): {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        owner: value.owner,
        profileId: value.profileId,
        description: value.description,
        category: from_candid_ResourceCategory_n25(_uploadFile, _downloadFile, value.category),
        startDate: value.startDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: [] | [string];
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address: string;
    functions: Array<_FunctionType>;
    phone: string;
    profilePicture: [] | [string];
}): {
    id: string;
    bio?: string;
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address: string;
    functions: Array<FunctionType>;
    phone: string;
    profilePicture?: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bio)),
        organizationName: value.organizationName,
        owner: value.owner,
        resources: value.resources,
        email: value.email,
        needs: value.needs,
        address: value.address,
        functions: from_candid_vec_n30(_uploadFile, _downloadFile, value.functions),
        phone: value.phone,
        profilePicture: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: _ResourceCategory;
}): {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        owner: value.owner,
        profileId: value.profileId,
        description: value.description,
        category: from_candid_ResourceCategory_n25(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resourceIds: Array<string>;
    needIds: Array<string>;
    category: _ResourceCategory;
}): {
    resourceIds: Array<string>;
    needIds: Array<string>;
    category: ResourceCategory;
} {
    return {
        resourceIds: value.resourceIds,
        needIds: value.needIds,
        category: from_candid_ResourceCategory_n25(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JoinRequestStatus;
    principal: Principal;
    displayName: [] | [string];
    profileId: string;
}): {
    status: JoinRequestStatus;
    principal: Principal;
    displayName?: string;
    profileId: string;
} {
    return {
        status: from_candid_JoinRequestStatus_n43(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.displayName)),
        profileId: value.profileId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: [] | [string];
    role: _ProfileRole;
}): {
    principal: Principal;
    displayName?: string;
    role: ProfileRole;
} {
    return {
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.displayName)),
        role: from_candid_ProfileRole_n53(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    activityType: _SuspiciousActivityType;
    timestamp: bigint;
    details: string;
}): {
    principal: Principal;
    activityType: SuspiciousActivityType;
    timestamp: bigint;
    details: string;
} {
    return {
        principal: value.principal,
        activityType: from_candid_SuspiciousActivityType_n59(_uploadFile, _downloadFile, value.activityType),
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n64(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storageSpace: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    publicity: null;
} | {
    foodDrink: null;
} | {
    distributionSpace: null;
} | {
    kitchenSpace: null;
}): ResourceCategory {
    return "storageSpace" in value ? ResourceCategory.storageSpace : "other" in value ? ResourceCategory.other : "equipment" in value ? ResourceCategory.equipment : "publicity" in value ? ResourceCategory.publicity : "foodDrink" in value ? ResourceCategory.foodDrink : "distributionSpace" in value ? ResourceCategory.distributionSpace : "kitchenSpace" in value ? ResourceCategory.kitchenSpace : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    production: null;
} | {
    education: null;
} | {
    equipmentSpace: null;
} | {
    wasteManagement: null;
} | {
    processing: null;
} | {
    distribution: null;
}): FunctionType {
    return "production" in value ? FunctionType.production : "education" in value ? FunctionType.education : "equipmentSpace" in value ? FunctionType.equipmentSpace : "wasteManagement" in value ? FunctionType.wasteManagement : "processing" in value ? FunctionType.processing : "distribution" in value ? FunctionType.distribution : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): JoinRequestStatus {
    return "pending" in value ? JoinRequestStatus.pending : "denied" in value ? JoinRequestStatus.denied : "approved" in value ? JoinRequestStatus.approved : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    clubAdmin: null;
}): ProfileRole {
    return "user" in value ? ProfileRole.user : "clubAdmin" in value ? ProfileRole.clubAdmin : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repeatedFailedRegistration: null;
} | {
    unusualPattern: null;
} | {
    rapidAccountCreation: null;
}): SuspiciousActivityType {
    return "repeatedFailedRegistration" in value ? SuspiciousActivityType.repeatedFailedRegistration : "unusualPattern" in value ? SuspiciousActivityType.unusualPattern : "rapidAccountCreation" in value ? SuspiciousActivityType.rapidAccountCreation : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Need>): Array<Need> {
    return value.map((x)=>from_candid_Need_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FunctionType>): Array<FunctionType> {
    return value.map((x)=>from_candid_FunctionType_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResourceHave>): Array<ResourceHave> {
    return value.map((x)=>from_candid_ResourceHave_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JoinRequest>): Array<JoinRequest> {
    return value.map((x)=>from_candid_JoinRequest_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfileMember>): Array<ProfileMember> {
    return value.map((x)=>from_candid_ProfileMember_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SuspiciousActivityFlag>): Array<SuspiciousActivityFlag> {
    return value.map((x)=>from_candid_SuspiciousActivityFlag_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n62(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_FunctionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FunctionType): _FunctionType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): _ProfileRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FunctionType): {
    production: null;
} | {
    education: null;
} | {
    equipmentSpace: null;
} | {
    wasteManagement: null;
} | {
    processing: null;
} | {
    distribution: null;
} {
    return value == FunctionType.production ? {
        production: null
    } : value == FunctionType.education ? {
        education: null
    } : value == FunctionType.equipmentSpace ? {
        equipmentSpace: null
    } : value == FunctionType.wasteManagement ? {
        wasteManagement: null
    } : value == FunctionType.processing ? {
        processing: null
    } : value == FunctionType.distribution ? {
        distribution: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    storageSpace: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    publicity: null;
} | {
    foodDrink: null;
} | {
    distributionSpace: null;
} | {
    kitchenSpace: null;
} {
    return value == ResourceCategory.storageSpace ? {
        storageSpace: null
    } : value == ResourceCategory.other ? {
        other: null
    } : value == ResourceCategory.equipment ? {
        equipment: null
    } : value == ResourceCategory.publicity ? {
        publicity: null
    } : value == ResourceCategory.foodDrink ? {
        foodDrink: null
    } : value == ResourceCategory.distributionSpace ? {
        distributionSpace: null
    } : value == ResourceCategory.kitchenSpace ? {
        kitchenSpace: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): {
    user: null;
} | {
    clubAdmin: null;
} {
    return value == ProfileRole.user ? {
        user: null
    } : value == ProfileRole.clubAdmin ? {
        clubAdmin: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FunctionType>): Array<_FunctionType> {
    return value.map((x)=>to_candid_FunctionType_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
